version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # RabbitMQ Management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASSWORD: password
  
  notification_service:
    build:
      context: ./NotificationService
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
    volumes:
      - ./log:/app/log

  email_service:
    build:
      context: ./EmailService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./log:/app/log

  sms_service:
    build:
      context: ./SMSService
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - ./log:/app/log

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"