global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'notification_service'
    static_configs:
      - targets: ['notification_service:5000']
  
  - job_name: 'email_service'
    static_configs:
      - targets: ['email_service:5001']

  - job_name: 'sms_service'
    static_configs:
      - targets: ['sms_service:5002']